/**
 * This file was generated by https://gitlab.com/vincenttunru/rdf-namespaces
 */

type Property = string;
type Class = string;
type Datatype = string;
type OwlClass = string;
type OwlObjectProperty = string;

/**
 * credText
 * 
 * The plaintext of a credential in a transaction
 *
 * http://dig.csail.mit.edu/2018/svc#credText
 */
export const credText: Property = 'http://dig.csail.mit.edu/2018/svc#credText';

/**
 * signedCred
 * 
 * The value of the signed credential in a transaction
 *
 * http://dig.csail.mit.edu/2018/svc#signedCred
 */
export const signedCred: Property = 'http://dig.csail.mit.edu/2018/svc#signedCred';

/**
 * prevTxn
 * 
 * The link to the previous transaction
 *
 * http://dig.csail.mit.edu/2018/svc#prevTxn
 */
export const prevTxn: Property = 'http://dig.csail.mit.edu/2018/svc#prevTxn';

/**
 * prevHash
 * 
 * The hash of the previous transaction
 *
 * http://dig.csail.mit.edu/2018/svc#prevHash
 */
export const prevHash: Property = 'http://dig.csail.mit.edu/2018/svc#prevHash';

/**
 * issuer
 * 
 * The public key of the issuer of a transaction
 *
 * http://dig.csail.mit.edu/2018/svc#issuer
 */
export const issuer: Property = 'http://dig.csail.mit.edu/2018/svc#issuer';

/**
 * subject
 * 
 * The public key of the subject of a transaction
 *
 * http://dig.csail.mit.edu/2018/svc#subject
 */
export const subject: Property = 'http://dig.csail.mit.edu/2018/svc#subject';

/**
 * timestamp
 * 
 * The timestamp of the creation of a transaction
 *
 * http://dig.csail.mit.edu/2018/svc#timestamp
 */
export const timestamp: Property = 'http://dig.csail.mit.edu/2018/svc#timestamp';

/**
 * Transaction
 * 
 * The class of linked transactions, representing statements, attestations, and credentials about an entity
 *
 * http://dig.csail.mit.edu/2018/svc#Transaction
 */
export const Transaction: Class = 'http://dig.csail.mit.edu/2018/svc#Transaction';
